# Generated by Django 2.0.8 on 2019-06-19 11:22

from django.db import migrations


def forwards_create_dummy_test(apps, schema_editor):
    TestModel = apps.get_model("demo", "TestModel")

    TestModel.objects.bulk_create(
        [TestModel(name="new test {}".format(i)) for i in range(5)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_create_dummy_test, migrations.RunPython.noop)
    ]
