# Generated by Django 3.1.7 on 2021-03-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_auto_20190619_1122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testmodel",
            options={
                "verbose_name": "test model",
                "verbose_name_plural": "test models",
            },
        ),
    ]
