# Generated by Django 3.2.6 on 2021-08-04 08:28

from django.db import migrations


def forwards_func(apps, schema_editor):
    Library = apps.get_model("custom", "Library")

    Library.objects.bulk_create(
        [Library(name="test library {}".format(i)) for i in range(5)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func, migrations.RunPython.noop)]
